batch_size: 16
learning_rate: 5e-5
num_epochs: 3
output_dir: outputs/real-env-grpo-gpu-20250810-005152
save_every: 1
use_mixed_precision: true
use_wandb: true
use_weave: true
warmup_steps: 100
weight_decay: 0.01
